### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar una pelicula por id
GET http://localhost:3000/movies/ccf36f2e-8566-47f7-912d-9f4647250bc7

### Bad (RECUPERAR UNA PELICULA POR ID QUE NO EXISTE)
GET http://localhost:3000/movies/1

### Recuperar una pelicula por género ****
GET http://localhost:3000/movies?genre=Fantasy
### Crear una pelicula CON POST
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Shrek 2",
  "year": 2004,
  "director": "Andrew Adamson",
  "duration": 93,
  "poster": "https://moviepostermexico.com/cdn/shop/products/shrek_two_ver1_xxlg_1024x1024@2x.jpg",
  "genre": [
    "Fantasy", 
    "Animation"
    ]
}
### Copy
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}
### new movie test
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "title movie",
  "year": 2024,
  "director": "-----------",
  "duration": 0,
  "poster": "https://link.jpg",
  "genre": [
    "Romance",
    "Sci-Fi"
  ]
}

### Actualizar una pelicula por id
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "title": "Hola",
  "year": 1995
}